### ISSUE TITLE
SyntaxError: Unmatched Selector

### ISSUE THREAD

**Issue by chilledtonic** [remy/wm#49]
When running ```wm``` on my RSS feed, I get this error:

```
limit = 1
send = false
Fetching https://cannedfi.sh/posts/index.xml
Content is RSS
entries = 1
SyntaxError: Unmatched selector: &rsquo;ve been investigating more deeply about Indieweb, namely their idea of a permashortlink - put succinctly, it is inevitable that shortlinking providers will either
Fold, or Deprecate underused links. This means that relying on them - and they are awfully convenient - is a net negative to the longevity of any web content you produce - and we&rsquo;ve already seen it happen.
The Indieweb solution to this deprecation problem is, of course - to roll your own.
    at parse (/usr/lib/node_modules/@remy/webmention/node_modules/css-what/index.js:85:9)
    at compileUnsafe (/usr/lib/node_modules/@remy/webmention/node_modules/css-select/lib/compile.js:31:14)
    at select (/usr/lib/node_modules/@remy/webmention/node_modules/css-select/index.js:18:49)
    at CSSselect (/usr/lib/node_modules/@remy/webmention/node_modules/css-select/index.js:41:9)
    at exports.find (/usr/lib/node_modules/@remy/webmention/node_modules/cheerio/lib/api/traversing.js:40:21)
    at module.exports (/usr/lib/node_modules/@remy/webmention/node_modules/cheerio/lib/cheerio.js:86:18)
    at new initialize (/usr/lib/node_modules/@remy/webmention/node_modules/cheerio/lib/static.js:29:20)
    at initialize (/usr/lib/node_modules/@remy/webmention/node_modules/cheerio/lib/static.js:26:14)
    at $ (/usr/lib/node_modules/@remy/webmention/lib/rss/dom.js:49:14)
    at /usr/lib/node_modules/@remy/webmention/lib/links.js:14:18
    at /usr/lib/node_modules/@remy/webmention/lib/rss/dom.js:23:16
    at Array.map (<anonymous>)
    at Object.map (/usr/lib/node_modules/@remy/webmention/lib/rss/dom.js:22:25)
    at links (/usr/lib/node_modules/@remy/webmention/lib/links.js:13:6)
    at Webmention.getLinksFromFeed (/usr/lib/node_modules/@remy/webmention/lib/webmention.js:52:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm not sure what selector it's trying to match, so this is difficult to troubleshoot for me. All pages on my site are microformats2 compliant, and the RSS feed itself passes all my validity checks - so I'm at a loss.

**Comment by chilledtonic** [comment]
The tool does not fail if I run it manually on the page it's tripping on; I see a few other closed issues with the same error message - though perhaps not the same cause - but there's no information on the source of the problem, they've all just been closed - I don't think the PR referenced in any of them is the solution to my current issue.

#32 
#28 
#7

**Comment by aciccarello** [comment]
I don't see this with the latest build. The fix in db824e5 is NOT on npm yet though.
